# Generated by Django 3.1.3 on 2025-07-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250724_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='historicalcategoryproduct',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='delated_day',
            new_name='deleted_day',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delated_day',
            new_name='deleted_day',
        ),
    ]
