# Generated by Django 3.1.3 on 2025-07-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250724_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='category',
            new_name='category_product',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='measuere_unit',
            new_name='measure_unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='measuere_unit',
            new_name='measure_unit',
        ),
    ]
